### ISSUE TITLE
Add argument to allow for loading of Fusion profiles

### ISSUE THREAD

**Issue by windows2000bug** [tylerszabo/RGB-Fusion-Tool#12]
This might not be all that difficult as RGB profiles for custom profiles are saved into user defined XML files. 

This might make it easier in two ways, you don't have to account for a lot of user errors and variations as the profiles are created by users who can easily set each profile up in the Fusion interface. Also the profiles will have the same structure so there should be less logic and error checking between different motherboards. 

Where I am going with this is that users create profiles and then we can create a job that runs every minute to check for user specified processes. If that process exists, then it will set set the profile to the one user specified. This would require a small config with process and their associated profiles.

**Comment by tylerszabo** [comment]
This is related to issue #2.

**Comment by tylerszabo** [comment]
I looked at the XML format for RGB Fusion - supporting that XML is likely better done by an external tool/script such as the https://github.com/windows2000bug/RGB-Fusion-Tool-PS script. I'm going to close this for now as out of scope.
