### ISSUE TITLE
Add color to be set by decimal number

### ISSUE THREAD

**Issue by windows2000bug** [tylerszabo/RGB-Fusion-Tool#17]
The XML profiles have a ARGB value as a decimal number. It looks like the tool only accepts the strings in color name and hexadecimal value.

I took the xml profile files created by Fusion and put it into a .\profiles folder in the root directory of CLI tool. My plan is to name the xml files the name of the corresponding process. If the powershell script detects the process running, it will set the color of each zone based off the details in the XML. This will make it more user friendly as profiles can be setup by Fusion's UI. I am messing around with formatting, though powershell is completely different in annoying way, compared to any othe language I have used. I might just convert the dec to hex myself in powershell, don't know if this would be easy to add or not for you.

**Comment by tylerszabo** [comment]
Related to #12. Could you attach example XML?

**Comment by windows2000bug** [comment]
Attached is the XML file, I changed the extension to *.txt, so I could upload it to here.

[Overwatch.xml.txt](https://github.com/tylerszabo/RGB-Fusion-Tool/files/1936279/Overwatch.xml.txt)

I am trying to parse the XML via power shell and was hoping it would be a little easier, I am a not really good at powershell so figuring out how things are done can be a little frustrating at times.  When/if profiles can be imported it would render what I am doing moot, though at the same time I enjoy the challenge, just hate getting hung up on hick ups on syntax differences.

**Comment by windows2000bug** [comment]
My hex hell was due to the fact I was trying to convert a string, when I really need a long/int64 ><.

**Comment by tylerszabo** [comment]
After reviewing the XML file it seems that this is more an artifact of odd casting behavior and best handled in an external script (see #12).
