### ISSUE TITLE
Need Arguements for Pulse/flash

### ISSUE THREAD

**Issue by windows2000bug** [tylerszabo/RGB-Fusion-Tool#21]
In the UI these are the only settings:
Pulse: speed and color
Flash: speed, color, and brightness

When you enter a command there is no list of required arguments in the output:

PS C:\Users\israel\Desktop\RGBFusionTool-PS> .\RGBFusionTool.exe -v --pulse=Red --speed=7
Zone 0: A_LED
Zone 1: A_LED
Zone 2: A_LED
Zone 3: A_LED
Zone 4: A_LED
Zone 5: NA
Zone 6: NA
Zone 7: D_LED_TYPE_2
Zone 8: D_LED_TYPE_2
.\RGBFusionTool.exe : Usage: RGBFusionTool.exe [OPTION]... [[LEDSETTING] | [ZONE LEDSETTING]...]
At line:1 char:1
+ .\RGBFusionTool.exe -v --pulse=Red --speed=7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Usage: RGBFusio...LEDSETTING]...]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Set RGB Fusion motherboard LEDs
Options:
  -
v, --verbose              
  -l
, 
--list                 list zones
  -
?, -h, 
--
help             show help and exit
ZONE:
  -
z, --zone
=VALUE
           set zone
LEDSETTING options:
Static color
  -c, 
--color, --static=VALUE
                             set static color
  -b
, 
--brightness=VALUE     
(optional) brightness (0-100)
Color cycle
      --cycle, --colorcycle[=SECONDS
]
                             cycle colors, changing color every SECONDS
  -b, 
--
brightness=VALUE     (optional) brightness (0-100)
Error: System.InvalidOperationException: No LED mode specified
   at RGBFusionTool.Application.Main(String[] args)

**Comment by tylerszabo** [comment]
Verify you're using version 0.9.0.6

**Comment by tylerszabo** [comment]
Output of `--help` on 0.9.0.6 should be:

```
Usage: RGBFusionTool.exe [OPTION]... [[LEDSETTING] | [ZONE LEDSETTING]...]
Set RGB Fusion motherboard LEDs

Options:
  -v, --verbose
  -l, --list                 list zones
  -?, -h, --help             show help and exit

ZONE:
  -z, --zone=VALUE           set zone

LEDSETTING options:

Static color
  -c, --color, --static=COLOR
                             set static color to COLOR
  -b, --brightness=VALUE     (optional) brightness (0-100)

Color cycle
      --cycle, --colorcycle[=SECONDS]
                             cycle colors, changing color every SECONDS
  -b, --brightness, --maxbrightness=VALUE
                             (optional) brightness (0-100)
      --cyclepulse           (optional) pulse between colors
      --minbrightness=VALUE  (optional) minimum brightness (during pulse) (0-
                               100)
      --numcolors=VALUE      (optional) number of colors to cycle (1-7 ->
                               ROYGBIV)

Pulse
      --pulse=COLOR          pulse color COLOR
      --maxbrightness=VALUE  (optional) max brightness (0-100)
      --minbrightness=VALUE  (optional) min brightness (0-100)
      --fadeon=SECONDS       (optional) fade on time (SECONDS)
      --fadeoff=SECONDS      (optional) fade off time (SECONDS)

Flash
      --flash=COLOR          flash color COLOR
      --maxbrightness=VALUE  (optional) max brightness (0-100)
      --minbrightness=VALUE  (optional) min brightness (0-100)
      --time=SECONDS         (optional) SECONDS to flash for
      --interval=SECONDS     (optional) SECONDS in a flash interval
      --flashcycle=SECONDS   (optional) SECONDS in a cycle
      --count=COUNT          (optional) flash COUNT intervals in a cycle

Off
      --off                  turn off
```
