### ISSUE TITLE
Add Support for Digital RGB LEDs

### ISSUE THREAD

**Issue by windows2000bug** [tylerszabo/RGB-Fusion-Tool#22]
Digital LEDs are not supported with there various forms.

**Comment by tylerszabo** [comment]
Unfortunately I don't have the hardware to test this at the moment. I'll put some changes to this in another branch and I'll need some help from others to verify.

**Comment by windows2000bug** [comment]
No problem, I can test them. The offer is till there if you want me to send you a strip of ws2812.

**Comment by tylerszabo** [comment]
I've pushed a branch with some experimental changes 0d59962

**Comment by tylerszabo** [comment]
Here's a one-off build of 0d59962
[RGBFusionTool_Release.zip](https://github.com/tylerszabo/RGB-Fusion-Tool/files/2007518/RGBFusionTool_Release.zip)

**Comment by tylerszabo** [comment]
Here's a one-off build of [`0e8051f`](https://github.com/tylerszabo/RGB-Fusion-Tool/commit/0e8051f073740b356e07def373adf7c5dab814ba)

[RGBFusionTool_digital_0e8051f073740b356e07def373adf7c5dab814ba_16.zip](https://github.com/tylerszabo/RGB-Fusion-Tool/files/2223235/RGBFusionTool_digital_0e8051f073740b356e07def373adf7c5dab814ba_16.zip)

**Comment by tylerszabo** [comment]
One-off build of remaining digital modes (commit 887c1f0).

[RGBFusionTool_digital_887c1f0d4300e3069bf461fa31932f15afdedf22_20.zip](https://github.com/tylerszabo/RGB-Fusion-Tool/files/2227846/RGBFusionTool_digital_887c1f0d4300e3069bf461fa31932f15afdedf22_20.zip)

**Comment by tylerszabo** [comment]
Now mainline in commit `52a0d0e18c09f9c35bc6235b682f811f463aba29`
