### ISSUE TITLE
Change SDK Link on README.md

### ISSUE THREAD

**Issue by windows2000bug** [tylerszabo/RGB-Fusion-Tool#26]
Current Link for RGB Fusion SDK in README.md provides the users with latest API, which is API 1.1. 1.1 is not compatible with the RGB-Fusion-Tool at this time. The link below is a direct link to the API 1.0, which will provide users who wish to compile with the proper SDK version. 

https://www.gigabyte.com/WebPage/332/images/B17.0926.1.zip

**Comment by tylerszabo** [comment]
1.1 should be compatible; I tested it just now. That fix was made in 9.0.0.3 - check you are using the correct version.
