### ISSUE TITLE
dllexp_GetMaxDivision returned 0xFFFFFFFF

### ISSUE THREAD

**Issue by Kingpark2394** [tylerszabo/RGB-Fusion-Tool#27]
After trying multiple rebuilds, versions of the SDK, and Git releases, I keep running into a similar error that I can't quite understand:

Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> GLedApiDotNet.Raw.GLedAPIv1_0_0Exception: dllexp_GetMaxDivision returned 0xFFFFFFFF
   at GLedApiDotNet.Raw.GLedAPIv1_0_0Wrapper.GetMaxDivision() in C:\Users\AJ\Downloads\RGB-Fusion-Tool-master\RGB-Fusion-Tool-master\GLedApiDotNet\Raw\GLedAPIv1_0_0Wrapper.cs:line 54
   at GLedApiDotNet.RGBFusionMotherboard..ctor(GLedAPIv1_0_0Wrapper wrapperAPI) in C:\Users\AJ\Downloads\RGB-Fusion-Tool-master\RGB-Fusion-Tool-master\GLedApiDotNet\RGBFusionMotherboard.cs:line 152
   at GLedApiDotNet.RGBFusionMotherboard..ctor() in C:\Users\AJ\Downloads\RGB-Fusion-Tool-master\RGB-Fusion-Tool-master\GLedApiDotNet\RGBFusionMotherboard.cs:line 163
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at RGBFusionTool.RGBFusionMain.LazyMotherboard.SetAll(LedSetting ledSetting) in C:\Users\AJ\Downloads\RGB-Fusion-Tool-master\RGB-Fusion-Tool-master\RGBFusionTool\RGBFusionMain.cs:line 25
   at RGBFusionTool.Application.Main(String[] args) in C:\Users\AJ\Downloads\RGB-Fusion-Tool-master\RGB-Fusion-Tool-master\RGBFusionTool\Application.cs:line 201

The only command I can execute and get anything other than this error is --help

**Comment by tylerszabo** [comment]
The main error here is `dllexp_GetMaxDivision` returned `0xFFFFFFFF`.

The doc `RGB Fusion Software Development Kit Guide.pdf` (in the SDK zip) show the following for `dllexp_GetMaxDivision`:

"Return Values
Returns the maximum number of LED zones that the MCU currently supports if success;
otherwise -1 is returned."

What motherboard do you have (and if you know your BIOS version that'd help, too)? At the point in the initialization where it's failing for you it really hasn't done much at all.

Other things to try will be running it elevated (Gigabyte's sample code requires elevation but I've found it's not always required. I don't know why they need it or when they need it.)

Another thing I'm thinking is that I'm packaging the 2017 (1.0.0) SDK with the release and the 2018-02-06 (1.1.0) version of the SDK (allegedly) added support for H310/B360/H370 and AX470 series boards. I say allegedly because the release notes also say it supports graphics cards and peripherals but the 1.1.0 release package does not expose the APIs they describe in the documentation.

**Comment by tylerszabo** [comment]
I'd also like to thank you for testing this and finding the issue :) - I only have the one environment so I really rely on others to make it robust.

**Comment by Kingpark2394** [comment]
Thanks for the quick response! I'm on a Gigabyte GA-AB350-Gaming 3 motherboard on BIOS F22. I haven't had any luck getting the actual RGB Fusion software to even install, and Gigabyte support has been no help so far, so I am really hoping we can get this to work!

**Comment by tylerszabo** [comment]
From what I can tell debugging it looks like there's a lot of places where failure is possible. So `GLedApiDotNet.dll` (the, thankfully, open source) calls `GLedAPI.dll` (At this point and below no source code or debug symbols) calls `ycc.dll` which seems to call `SMBCtrl.dll` and `gdrv.sys` (which should be installed with motherboard drivers). My best guess is that it's just pushing data into a some microcontroller's memory and letting it go drive the LEDs. So, the next thing I'm thinking is that you might not have the most featureful chipset driver installed. Have you installed [this](https://www.gigabyte.com/us/Motherboard/GA-AB350-Gaming-3-rev-1x#support-dl-driver-chipset)?

**Comment by tylerszabo** [comment]
I did some more investigation: one thing I notice is that I don't see the `B350` chipset listed in `layout.ini` which makes me think it might not be supported by the SDK they're putting out. I even looked at strings in `LedLib2.dll` (from the RGB Fusion installer) and it references the `B360` but not `B350`.

I would press Gigabyte that their RGB Fusion software isn't working and point out that their [website](https://www.gigabyte.com/Motherboard/GA-AB350-Gaming-3-rev-1x#kf) states "LED enthusiasts now have even more options with the ability to customize multiple zones independently. For a more functional use, the bright and vibrant LEDs can be configured to display the PC’s temperature or load".

In addition the RGB Fusion SDK should also be supported as your motherboard is listed on the [supported products page](https://www.gigabyte.com/mb/rgb/Product).

I did see some reviews on Newegg that state "RGB Fusion only works in the BIOS, the software does nothing" and "RGB Fusion app on the pc it self refuses to work I am looking into fixing this looking into this and it's not the board it is the software." and one on Amazon that seemed to say something similar. So it would seem you're not the only one with this kind of issue.

The only other thing I can think of is if you have a CD that came with the motherboard that has a super-special version of RGB Fusion that does support your board.

For the time being until you have more information I'd like to keep this bug open (especially in case someone has a similar issue) but I think we need more information from Gigabyte to proceed.

**Comment by Kingpark2394** [comment]
Whoops....the AB350M Gaming-3 (the actual board that I have) does _not_ support RGB fusion, but the product page on a few sites shows the AB350 Gaming 3 (full sized version WITH RGB Fusion) in the product description for the AB350M. So, apparently my board does not even support this at all, which is why it does not work. At least I'm not the only one who was incredibly confused by this, it just seems like a poor mix of bad naming conventions, misleading product info on multiple websites, and already buggy software in general. Sorry for wasting your time by providing the wrong MoBo info, but at least we both know now for a fact that the AB350_m_ Gaming 3 does not support RGB Fusion, but the AB350 (standard) Gaming 3 _does_.

**Comment by tylerszabo** [comment]
Aha! Good find. There's some additional good news in this: now we know the behavior of the tool when the motherboard is still a Gigabyte board but doesn't have RGB Fusion support! If you are doing other RGB stuff I came across this really interesting project recently: https://github.com/DarthAffe/RGB.NET so you might be able to get similar functionality out of it with your other RGB stuff :)
