### ISSUE TITLE
Support setting individual divisions (zones)

### ISSUE THREAD

**Issue by tylerszabo** [tylerszabo/RGB-Fusion-Tool#3]

**Comment by tylerszabo** [comment]
Poll data: https://www.facebook.com/groups/AORUS/permalink/2042306429378673/

**Comment by windows2000bug** [comment]
This works great! Though it looks like the zone details is omitted from output, when verbose flag is set.

**Comment by tylerszabo** [comment]
Thanks for confirming, noted the verbose issue with #14. Closing this issue :)

**Comment by tylerszabo** [comment]
Reopening issue to track
