### ISSUE TITLE
Linux / through Wine

### ISSUE THREAD

**Issue by cdrage** [tylerszabo/RGB-Fusion-Tool#35]
Any possibility / plans on getting this to run through Linux or Wine?

The problem would most likely be trying to reverse engineer the SDK...

**Comment by tylerszabo** [comment]
If the an SDK for Linux was available (or a specification so we can write one to talk directly to the hardware) I'd certainly be up to trying to target Linux (I'd rather target an open SDK anyway).

Unfortunately I haven't been able to find any documentation. If you find a spec or an SDK with Linux support please ping me and I'll look at it.

I don't think Wine would even be needed, this project *should* work with Mono (looks like some [pinvoke](https://www.mono-project.com/docs/advanced/pinvoke/) fancy business can be done to be cross-platform compatible when loading native libraries, too, but that can also be done with some wrappers).

Please do open a ticket with Gigabyte - even if they open source their current SDK then we could look into porting it.

**Comment by cdrage** [comment]
@tylerszabo Alright. I'll try it out and let you know if it works.

Yeah... I *really* wish that Gigabyte would release a Linux SDK but to no avail :-1: :unamused:

**Comment by cdrage** [comment]
@tylerszabo On a side note, do you know off by hand if the LEDs are controlled through the Super IO / ITE Super IO chipset?

I'm looking at https://github.com/xdarklight/gigabyte_ambientled_ctrl and I'm hoping to reverse engineer his implementation and figure out what the appropriate commands are to send to the chipset.

**Comment by cdrage** [comment]
One of the things is trying to figure out the NUM and PIN values:

```sh
        local GPIO_BANK_NUM=${1}
	local GPIO_BANK_PIN=${2}
	local GPIO_VALUE=${3}
```

Of what to send to the IT87 chipset.

**Comment by tylerszabo** [comment]
I'm afraid I don't know what Gigabyte uses to talk to the hardware.

**Comment by windows2000bug** [comment]
@cdrage Are you sure about that, according to tweak town the IT87 is to help control the fans. 
"The ITE IT8295FN microcontroller is used to control all the RGB LEDs and provides the digital RGB capabilities on the motherboard. The IT8795E is used as an embedded controller, and it provides extra fan control support."

Source: https://www.tweaktown.com/reviews/8377/gigabyte-z370-aorus-gaming-7-motherboard-review/index4.html

Also AlphaC from OCN says the same thing, for the x470 Gaming 7: 
source: https://www.overclock.net/forum/11-amd-motherboards/1689225-gigabyte-x470-aorus-gaming-7-wifi-overclocking-discussion-thread.html

I don't see a datasheet on the IT8295FN, don't see many from ITE, though if you google "site:http://www.ite.com.tw/uploads/product_download", you can see a few PDFs. From there you could simply write a script to try a few variations of the "IT8295_V<number>_<datestamp>.pdf"

I messed around with it a little bit and didn't find anything, though didn't write a script either. 

Browsing their site I found this: http://www.ite.com.tw/en/product/view?mid=120

**Comment by cdrage** [comment]
@windows2000bug 

Yeah, so after getting the datasheet it'd be pretty straight-forward.

I'll try to see if I can get it, but no promises. I'd love to find it as it'd be as easy as sending a few commands to the PIN.
