### ISSUE TITLE
How to I upgrade to 0.9.3.7?

### ISSUE THREAD

**Issue by thisismikedee** [tylerszabo/RGB-Fusion-Tool#43]
I installed 0.9.2 via choco, how do I upgrade it? I want to try the new digital stuff you added and hopefully my Aorus ram works with the new version. Everything else has been FANTASTIC.

**Comment by tylerszabo** [comment]
Right now it'd be manually by unzipping from one of the GitHub [releases](https://github.com/tylerszabo/RGB-Fusion-Tool/releases). It wasn't stable enough to put it into Chocolatey, yet (didn't want to break anyone) especially with the dependency situation. Once #25 is closed to add more robust dependency checking (and not crash if the peripheral DLLs can't enumerate) then I'd be more comfortable.

Mostly, I want the Chocolatey package to be a bit more robust such that "latest" there is going to be stable.
