### ISSUE TITLE
Any plans for Ubuntu/Unix support?

### ISSUE THREAD

**Issue by 2check91** [tylerszabo/RGB-Fusion-Tool#52]
A command line interface that leverages the RGB headers for Ubuntu would be really neat.  
I think it should be relatively easy to do as well. 

If anyone wants to point me towards the direction of where the controllers for the RGB header is in a Unix system, I'll see if I could hack something up really quick.

Btw, I'm on an X570 I Aorus Pro Wifi.

**Comment by tylerszabo** [comment]
Right now what I have is the SDK Gigabyte provides.

If I had more information I'd be open to it. I suspect it would require a specification or other documentation; then a kernel-land driver; then a user-land library to interact with the driver; then finally a tool to interact with that library (which is where this sits in Windows world).

As such I'd consider it out of scope for this particular project but certainly something I'd be interested in working on if I had more information. Though I only have the Z370 Gaming 7 to test on.

Given Gigabyte's lack of support when I (and others) have reached out I'd advocate using 3rd party hardware and if having onboard lighting is important finding another vendor.
