### ISSUE TITLE
Question: Does it require RGB Fusion 1.0 or 2.0 to be installed?

### ISSUE THREAD

**Issue by jmrnilsson** [tylerszabo/RGB-Fusion-Tool#53]
As per title.. ^

**Comment by tylerszabo** [comment]
Nope, if you have the DLLs listed in the [README ](https://github.com/tylerszabo/RGB-Fusion-Tool/blob/master/README.md) it stands alone.

**Comment by jmrnilsson** [comment]
Thank. Noticed ab350 gaming 3 not supported

**Comment by tylerszabo** [comment]
Unfortunately that's correct, issue #30 is tracking it. Gigabyte seems to have abandoned their SDK and haven't released any docs for how to integrate with other boards.

**Comment by jmrnilsson** [comment]
Yeah, I noticed. Their own app RGB Fusion is even getting more crippled in V.2.
