### ISSUE TITLE
Some zones don't switch color

### ISSUE THREAD

**Issue by windows2000bug** [tylerszabo/RGB-Fusion-Tool#9]
I am using the Z370 Gaming 7 motherboard and it looks like one or two of the zones doesn't switch colors when I set the color to red/blue/green, etc.

**Comment by tylerszabo** [comment]
What's the output from --list?

**Comment by windows2000bug** [comment]
RGBFusionTool.exe --list
Zone 0: A_LED
Zone 1: A_LED
Zone 2: A_LED
Zone 3: A_LED
Zone 4: A_LED
Zone 5: NA
Zone 6: NA
Zone 7: D_LED_TYPE_2
Zone 8: D_LED_TYPE_2

![image](https://user-images.githubusercontent.com/38469063/38905053-1480d79a-427c-11e8-9493-8b1d0874fcfc.png)

**Comment by tylerszabo** [comment]
Specifying a zone isn't supported yet, that's tracked by issue #3. I wanted to see if GLedAPI was reporting all of the zones.

**Comment by tylerszabo** [comment]
I'm testing on a Z370 AORUS Gaming 7

**Comment by windows2000bug** [comment]
When you run  "RGBFusionTool.exe -v --color blue" Do the RAM slots and lighting around VRM change color? 

OS: Windows 10 Home
MB: Gigabyte Z370 Gaming 7 Rev. 1.0
Bios: F6 and issue was there in F5
Fusion: B18.0413.1 and the previous release

**Comment by tylerszabo** [comment]
I was able to reproduce it

**Comment by windows2000bug** [comment]
Jus wondering is your two analog RGBW headers tied into the same channel?

**Comment by tylerszabo** [comment]
I don't have a strip to test with, so I'm not sure.

**Comment by tylerszabo** [comment]
Closing as this was fixed in PR #13
